import type { Metadata } from 'next'
import { Sidebar } from './components/sidebar'

export const metadata: Metadata = {
  title: 'Twitch Layout',
  description: 'Generated by Antonio',
}

export default function BrowsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {/* <Navbar /> */}
      <div className="flex h-full pt-20">
        <Sidebar />
        {/* <Suspense fallback={<SidebarSkeleton />}>
        </Suspense>
        <Container> */}
        {children}
        {/* </Container> */}
      </div>
    </>
  )
}
